contactform:
  description: Write your Message Here
  emailconfig: abc
facts:
  experience: 5
  projects: 25
  customers: 100
keywords: kaushal, patel,  portfolio, website, netlify, jekyll
author:
  resumelink: https://google.com
  name: Kaushal Patel
  cvlink: https://google.com
  phone: +91 63550 75156
  first: Kaushal
  address: Gujarat, IN
  last: Patel
  dob: 13 Jun 2002
  passion: Web Developer, Graphic Designer
  languages: English, Gujarati, Hindi
  image: /assets/uploads/img_4767.jpg
  nationality: INDIAN
  email: mr.kaushal.dev@gmail.com
  description: I am a Web Developer from India. I am very passionate and dedicated
    to my work. I have 3 years more work experience. I enjoy working in a team
    or individual.
social:
  facebook: mr.kaushal.p
  github: mrkp
  instagram: mr.kaushal.p
  linkedin: mrkaushalp
  twitter: mr_kaushal_p
  website: spece.netlify.app
collections:
  portfolio:
    output: true
title: Kaushal Patel
description: My Portfolio
baseurl: ""
